spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:pass}
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: ${DDL_AUTO:create}