spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:pass}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:create}
student-shell-service:
  enable-beans:
    student-generator: ${RANDOM_STUDENTS:false}